### PR TITLE
Add support for Modbus Must protocol

### PR DESCRIPTION
**Pull request by bigdigital**
Tested on Must PH18-3024, also should work on all pv/ph18 series
As hardware was used wemos d1 mini  controller + MAX485 module 
Connection diagram
modbus-must

The power for controller taken from USB output of the inverter  

The json data received from inverter
`{"DeviceData":{"Device_Model":"PH1800","Battery_type":"AGM","Battery_float_voltage":"27.0"},"LiveData":{"Inverter_Operation_Mode":"GridTie","Battery_Voltage":"27.5","Battery_Load":0,"AC_in_Voltage":"242.8","AC_in_Frequenz":"50.00","AC_out_Voltage":"242.6","AC_out_Frequenz":"50.01","Inverter_Bus_Voltage":"438.8","Output_load_percent":7,"PV_Input_Voltage":"105.8","PV_Charging_Power":88,"PV_Input_Current":"2.9","Inverter_Bus_Temperature":45,"Transformer_temperature":46,"MPPT1_Charger_Temperature":37}`

### CODE REVIEW

**Comment by LionBS76** [comment]
is it able to use RS485-UART board without RE/DE pins ? Only RX/TX.
Like this one board 
image

**Comment by softwarecrash** [comment]
> is it able to use RS485-UART board without RE/DE pins ? Only RX/TX. Like this one board image


normal yes. you can try it, but this boards most crap, the rs and serial chip are cheap fakes and most not work. but try it

**Comment by LionBS76** [comment]
> > is it able to use RS485-UART board without RE/DE pins ? Only RX/TX. Like this one board image + origin Solar Power Monitor from Must and it works.

**Comment by LionBS76** [comment]
> > is it able to use RS485-UART board without RE/DE pins ? Only RX/TX. 
> normal yes. you can try it, but this boards most crap, the rs and serial chip are cheap fakes and most not work. but try it

Hello.
It works.
But from Must inverter (PV18-3224) it gathering only 20 parameters.

image

**Comment by softwarecrash** [comment]
@LionBS76 what for parameters you are missing?

@bigdigital can you assist this?

**Comment by LionBS76** [comment]
> @LionBS76 what for parameters you are missing?
> 
> @bigdigital can you assist this?

I saw some interesting parameters in the origin Solar Power Monitor and want to research this parameters how can I use them efficiantly. 

Not full list of parameters:

- AccumulatedChargerPower	
- AccumulatedDischargerPower	
- AccumulatedBuyPower	
- AccumulatedSellPower	
- AccumulatedLoadPower	
- AccumulatedSelfusePower	
- AccumulatedPvsellPower	
- AccumulatedGridChargerPower
- WorkState	
- InverterRelayState	
- GridRelayState	
- LoadRelayState
- PInverter	
- PGrid	
- PLoad	
- Load percent	
- SInverter	
- SGrid	
- Sload	
- Qinverter	
- Qgrid	
- Qload

**Pull request merged**
