### PR TITLE
Add support of one Dallas DS18x20 temperature sensor

### PR DESCRIPTION
**Pull request by zholdak**
I'm suggest a simple support of one of Dallas DS18x20 temperature sensor. 
It should be connected by classical scheme into D5 (gpio14, can be changed through platfomio.ini) of the Wemos D1 mini.
It may be useful to control the environment temperature, for example, around of the inverter.
For now it simply publish the temperature into `Device/LiveData/External_Temperature` topic.

### CODE REVIEW

**Comment by softwarecrash** [comment]
hey,
i must refuse this PR.
please check my other projects like
https://github.com/softwarecrash/EPEver2MQTT
https://github.com/softwarecrash/Daly2MQTT
and add it in this way, its most copy&paste
so it needs:
- wireing diagram for wiki
- publish in mqtt/json/livejson
- automatic add to homeassistant

so its not nescary to modify the ini file or something.
please use the pin asgiment of the other projects, so we have PCB´s for solar too that have this pinout allready for sensors, i just forgott it to implement it in solar

**Comment by zholdak** [comment]
Ok, I understand. Thank you. It's my bad: I didn't look into the other projects, so, I'll rework it.

**Comment by softwarecrash** [comment]
> Ok, I understand. Thank you. It's my bad: I didn't look into the other projects, so, I'll rework it.

thank you, its realy just c&p and a little adjustment, then it will support automatic multiple sensors

**Comment by zholdak** [comment]
Hi.
It is small inconsistency with pin usage. In Solar2MQTT your are using gpio4 for leds (LED_NET). But in the EPEver2MQTT and Daly2MQTT gpio4 used for OneWire... In the Solar2MQTT it is need to use another pin (not gpio4, if you wish to leave it for leds) gpio14 (Wemos D5), for example, for OneWire.
That you think about that?

**Comment by all-solutions** [comment]
LED_NET is only relevant for the “dongle version”. For the installation of the DS18x20, #ifdef's must be integrated, which only defines LED_NET (and it's functions) if it is the dongle version.
The pin definitions must remain, otherwise people with the already purchased PCB will not be able to use them.
For the dongle version, however, LED_NET **must** remain as it is, as it is not possible to change the pin definitions on the purchased dongle (hard-wirered).

**Comment by zholdak** [comment]
Ok, let then for Solar2MQTT GPIO15 will be the OneWire pin (GPIO14 is already occupied by modbus RS485_DIR). But it shouldn't be relevant for all boards. For D1 mini -- yes, for esp01m -- looks like is yes too, but for WiFi dongle it is not.
_Crap! I'm already soldered it to GPIO14 on both devices (((_

**Comment by softwarecrash** [comment]
for the dongle version its not possbile to connect any other things, so a define to disable all ds18x functions or pin assigments for this version is enugh

**Pull request closed without merging**
